bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 180
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts

releases:
  - name: radar-appserver-postgresql
    chart: radar/postgresql
    version: {{ .Values.radar_appserver_postgresql._chart_version }}
    wait: false
    installed: {{ .Values.radar_appserver_postgresql._install }}
    values:
      - "../etc/radar-appserver-postgresql/values.yaml"
      - {{ .Values.radar_appserver_postgresql | toYaml | indent 8 | trim }}
    set:
      - name: global.postgresql.auth.postgresPassword
        value: {{ .Values.radar_appserver_postgres_password }}
      - name: auth.replicationPassword
        value: {{ .Values.radar_appserver_postgres_password }}

  - name: radar-appserver
    chart: radar/radar-appserver
    version: {{ .Values.radar_appserver._chart_version }}
    installed: {{ .Values.radar_appserver._install }}
    values:
      - {{ .Values.radar_appserver | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}
      - name: postgres.password
        value: {{ .Values.radar_appserver_postgres_password }}
